version: '0.1.2-beta-{build}'
platform: Any CPU
configuration: Release

image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: false

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -y

assembly_info:
  patch: true

before_build:
  - dotnet restore DotNetApiKeyAuth.sln
  - dotnet restore .\tests\ApiKeyAuth.Tests
build:
  project: DotNetApiKeyAuth.sln