version: '{build}'
image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: false

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -y

assembly_info:
  patch: true

before_build:
  - nuget restore DotNetApiKeyAuth.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b $env:APPVEYOR_REPO_BRANCH

build:
  project: DotNetApiKeyAuth.sln

after_build:
  - cmd: nuget pack ApiKeyAuth.nuspec -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

artifacts:
  - path: '*.nupkg'
    name: NuGet

deploy:
  - provider: Environment
    name: PreRelease NuGet Feed
    on:
      branch: master
  - provider: Environment
    name: Public NuGet Feed
    on:
      appveyor_repo_tag: true
